### ISSUE TITLE
`TypeError: Expected unicode, got float` on city selection click

### ISSUE THREAD

**Issue by gRizzlyGR** [GoBig87/NordVpnLinuxGUI#12]
Hi. The application, unfortunately, crashes when I select a city. Here are the steps:
- Run the application
- Click on a country (e.g. Albania)
- The application crashes.

The error seems in `ui/country_selection.py`. Here's an excerpt of the log:
```
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 5:
 ...
       3:    id: city_box
       4:    orientation: "vertical"
 >>    5:    spacing: dp(5), dp(10)
       6:    height: dp(50)
       7:    BoxLayout:
 ...
 TypeError: Expected unicode, got float
```

If I change to `spacing: str(dp(5)), str(dp(10))`, the application runs fine.

Here is the full error log:
```
 Traceback (most recent call last):
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 549, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 748, in kivy.properties.NumericProperty.convert
   File "kivy/properties.pyx", line 769, in kivy.properties.NumericProperty.parse_list
 TypeError: Expected unicode, got float
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 50, in <module>
     MainApp().run()
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/base.py", line 383, in idle
     self.dispatch_input()
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/base.py", line 334, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/base.py", line 302, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivymd/uix/behaviors/ripple_behavior.py", line 296, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivymd/uix/button.py", line 981, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 55, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 54, in <module>
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/ui/widgets/country_selection.py", line 114, in build_drop_down
     self.add_widget(CitySelection(city=city, connect=self.connect))
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/ui/widgets/country_selection.py", line 81, in __init__
     super().__init__(**kwargs)
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/uix/boxlayout.py", line 145, in __init__
     super(BoxLayout, self).__init__(**kwargs)
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 366, in __init__
     self.apply_class_lang_rules(
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/uix/widget.py", line 470, in apply_class_lang_rules
     Builder.apply(
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 540, in apply
     self._apply_rule(
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 709, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 5:
 ...
       3:    id: city_box
       4:    orientation: "vertical"
 >>    5:    spacing: dp(5), dp(10)
       6:    height: dp(50)
       7:    BoxLayout:
 ...
 TypeError: Expected unicode, got float
   File "/home/giuseppe/github.com/GoBig87/NordVpnLinuxGUI/venv/lib/python3.8/site-packages/kivy/lang/builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 549, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 748, in kivy.properties.NumericProperty.convert
   File "kivy/properties.pyx", line 769, in kivy.properties.NumericProperty.parse_li
```

My specs:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

**Comment by gRizzlyGR** [comment]
I can open a PR for fixing the issue, that is changing the line to `spacing: str(dp(5)), str(dp(10))`, but it seems a bit hack-ish and probably the error could pop up somewhere. Let me know if I can help with this, or if you need other info.

**Comment by GoBig87** [comment]
Looks like I put a tuple instead of a single value.  I think this PR should fix your issue https://github.com/GoBig87/NordVpnLinuxGUI/pull/13

**Comment by gRizzlyGR** [comment]
Indeed, thanks! This can be closed.
