### ISSUE TITLE
does not work on steam deck

### ISSUE THREAD

**Issue by Changshire** [GoBig87/NordVpnLinuxGUI#20]
It doesn't work on Steam deck, here is the log

```
3.11.3
/home/deck/Downloads/NordVpnLinuxGUI-main/installer.sh: line 4: pamac: command not found
[sudo] password for deck: 
Failed to enable unit: Unit file nordvpnd.service does not exist.
/home/deck/Downloads/NordVpnLinuxGUI-main/installer.sh: line 7: pamac: command not found
/home/deck/Downloads/NordVpnLinuxGUI-main/installer.sh: line 8: pamac: command not found
/home/deck/Downloads/NordVpnLinuxGUI-main/installer.sh: line 9: pamac: command not found
usermod: group 'nordvpn' does not exist
Requirement already satisfied: wheel in ./venv/lib/python3.11/site-packages (0.42.0)

[notice] A new release of pip available: 22.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer==2.0.9
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting docutils==0.18.1
  Using cached docutils-0.18.1-py2.py3-none-any.whl (570 kB)
Collecting idna==3.3
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting Kivy==2.1.0
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Kivy-Garden==0.1.4
  Using cached Kivy_Garden-0.1.4-py3-none-any.whl
Collecting kivy-garden.mapview==1.0.5
  Using cached kivy_garden.mapview-1.0.5-py3-none-any.whl (26 kB)
Collecting kivymd==0.104.2
  Using cached kivymd-0.104.2-py3-none-any.whl (2.3 MB)
Collecting mapview==1.0.5
  Using cached mapview-1.0.5-py3-none-any.whl (26 kB)
Collecting Pillow==8.4.0
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Preparing metadata (setup.py) ... done
Collecting Pygments==2.10.0
  Using cached Pygments-2.10.0-py3-none-any.whl (1.0 MB)
Collecting requests==2.26.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting urllib3==1.26.7
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Building wheels for collected packages: Kivy, Pillow
  Building wheel for Kivy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Kivy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [91 lines of output]
      [INFO   ] [Logger      ] Record log in /home/deck/.kivy/logs/kivy_23-12-25_5.txt
      [INFO   ] [Kivy        ] v2.1.0
      [INFO   ] [Kivy        ] Installed at "/tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb/kivy/__init__.py"
      [INFO   ] [Python      ] v3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
      [INFO   ] [Python      ] Interpreter at "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/bin/python3"
      [INFO   ] [Logger      ] Purge log fired. Processing...
      [INFO   ] [Logger      ] Purge finished!
       <string>:370: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:373: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:377: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       warning: kivy/graphics/common.pxi:9:4: 'const_char_ptr' redeclared
       warning: kivy/graphics/common.pxi:23:4: 'size_t' redeclared
      Current directory is: /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb
      Source and initial build directory is: /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb
      Python path is:
      /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb
      /home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process
      /tmp/pip-build-env-z8w9bvwz/site
      /usr/lib/python311.zip
      /usr/lib/python3.11
      /usr/lib/python3.11/lib-dynload
      /tmp/pip-build-env-z8w9bvwz/overlay/lib/python3.11/site-packages
      /tmp/pip-build-env-z8w9bvwz/normal/lib/python3.11/site-packages
      /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb/kivy/modules
      /home/deck/.kivy/mods
      
      
      Found Cython at /tmp/pip-build-env-z8w9bvwz/overlay/lib/python3.11/site-packages/Cython/__init__.py
      Detected supported Cython version 0.29.28
      Using this graphics system: OpenGL
      WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 127)
      
      b'/bin/sh: line 1: pkg-config: command not found\n'
      
      WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 127)
      
      b'/bin/sh: line 1: pkg-config: command not found\n'
      
      WARNING: A problem occurred while running pkg-config --libs --cflags pangoft2 (code 127)
      
      b'/bin/sh: line 1: pkg-config: command not found\n'
      
      ERROR: Dependency for context.pyx not resolved: config.pxi
      ERROR: Dependency for compiler.pyx not resolved: config.pxi
      ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for fbo.pyx not resolved: config.pxi
      ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for instructions.pyx not resolved: config.pxi
      ERROR: Dependency for opengl.pyx not resolved: config.pxi
      ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
      ERROR: Dependency for shader.pyx not resolved: config.pxi
      ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for texture.pyx not resolved: config.pxi
      ERROR: Dependency for vbo.pyx not resolved: config.pxi
      ERROR: Dependency for vertex.pyx not resolved: config.pxi
      ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for cgl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
      ERROR: Dependency for svg.pyx not resolved: config.pxi
      Building extensions in parallel using 4 cores
      Updated build directory to: build/lib.linux-x86_64-cpython-311
      Build configuration is:
       * use_rpi = 0
       * use_egl = 0
       * use_opengl_es2 = 0
       * use_opengl_mock = 0
       * use_sdl2 = 0
       * use_pangoft2 = 0
       * use_ios = 0
       * use_android = 0
       * use_mesagl = 0
       * use_x11 = 0
       * use_wayland = 0
       * use_gstreamer = 0
       * use_avfoundation = 0
       * use_osx_frameworks = 0
       * debug_gl = 0
       * kivy_sdl_gl_alpha_size = 8
       * debug = False
      Updated build/lib.linux-x86_64-cpython-311/kivy/include/config.h
      Updated /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb/kivy/include/config.h
      Updated build/lib.linux-x86_64-cpython-311/kivy/include/config.pxi
      Updated /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb/kivy/include/config.pxi
      Updated build/lib.linux-x86_64-cpython-311/kivy/setupconfig.py
      Updated /tmp/pip-install-de0smc2s/kivy_116a4e161b3544eaa51c1a7a8df70aeb/kivy/setupconfig.py
      Detected compiler is unix
       error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Kivy
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [185 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-de0smc2s/pillow_fb9be6f6f7154ef0a5f5e7f3e4915834/setup.py", line 978, in <module>
          setup(
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/deck/Downloads/NordVpnLinuxGUI-main/venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-de0smc2s/pillow_fb9be6f6f7154ef0a5f5e7f3e4915834/setup.py", line 790, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-de0smc2s/pillow_fb9be6f6f7154ef0a5f5e7f3e4915834/setup.py", line 1037, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Kivy Pillow
ERROR: Could not build wheels for Kivy, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
Creating desktop Icon
/home/deck/Downloads/NordVpnLinuxGUI-main/NordVPN.desktop
cp: cannot create regular file '/usr/share/applications/NordVPN.desktop': Read-only file system
cp: cannot stat '/usr/share/applications/NordVPN.desktop': No such file or directory
Finished Installation
To Enable desktop launching, right click on the NordVPN.desktop cog Icon and right click and select 'Allow Launching'
```

I know nothing about commands and linux so sorry in advance

**Comment by GoBig87** [comment]
You might have better luck using a repo like this https://github.com/steve228uk/TunnelDeck which installs openVPN and then you can use these (https://nordvpn.com/ovpn/) NordVPN config files with it.

If you really want to use my repo with your steam deck you'll need to find a way to install the nordvpn command line client on your steam deck.  Steam deck is a custom flavor of Arch Linux that unfornutely doesn't have the `pacman` package support for installing things.  Poking around some internet forums it looks like you might be able to get `pacman` working with

```
sudo steamos-readonly disable 
```
```
sudo pacman -S base-devel
```
then try and run my install script again once you have pacman support.  Note that any steam updates might overwrite your changes and you might need to install again.

**Comment by GoBig87** [comment]
Checkout this https://help.steampowered.com/en/faqs/view/671A-4453-E8D2-323C

Specifically 
`What if I want to do more than what’s available by flatpak?`
and
`How do I run sudo commands?`
both are needed to run a third party installer.

**Comment by Changshire** [comment]
Hey! thank you so much for your help! it looks like it helped and its done more than before, it still fails though unfortunately... i would rather not use openvpn cause i dont like only having one server and not having a quick connect for the server. i managed to install the CLI version of nord thanks to you so i'll manage :)
thanks again and good luck!
